#!/bin/bash

db="phone_book.db"

#If no argument is not passed to the script display the help menu
if [ -z $1 ]; then
	#Clear screen
	clear
	#Display help menu
	echo "+-------------------------------+"
	echo "               Phone             "
	echo "+-------------------------------+"
	echo "| -a to add a new phone record  |"
	echo "| -c to clear all records       |"
	echo "| -d to delete a phone record   |"
	echo "| -f to find a phone records    |"
	echo "| -v to view all phone records  |"
fi

# add
if [[ $1 == *"-a"* ]]; then
	clear
	echo -n "Enter Name: "
	read name
	echo -n "Enter Phone Number: "
	read phone
	echo $name $phone >> $db
	echo "Address Added."
fi

# display
if [[ $1 == *"-v"* ]]; then
	clear
	nl --number-separator=":    " $db | less
fi

#search
if [[ $1 == *"-f"* ]]; then
	clear
	echo -n "Enter a name or phone number: "
	read f
	grep -i $f $db
fi

#delete
if [[ $1 == *"-d"* ]]; then
	clear
    echo -n "Enter a record number to delete: "
    read n
    mv $db temp.txt
	clear
    nl --number-separator=":" temp.txt | grep -v $n: | awk -F: '{print $2}' |  tee $db
fi
#clear
if [[ $1 == *"-c"* ]]; then
	echo "Add phone records have been deleted."
	
	echo > $db
fi
